services:

  api:
    container_name: api-Backend
    build: .
    volumes:
      - .\\certs\\.aspnet\\https:/https/
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT:7022
      - ASPNETCORE_Kestrel__Certificates__Default__Password=supersecret
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "7021:80"
      - "7022:443"
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: es2
    build: ./InvBank.Backend.Infrastructure/Database/.
    volumes:
      - pg-data:/var/lib/postgresql/shared-data/
    ports:
      - "${EXP_PORT_PG}:5432"
    environment:
      - "POSTGRES_USER=${EXP_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${EXP_POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${EXP_POSTGRES_DB}"
    networks:
      - app-network

  reiport_db_interface:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  pg-data:
  api-data:


networks:
  app-network:
    driver: bridge
